export const types = {
  FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  FETCH_USER_POSTS_SUCCESS: "FETCH_USER_POSTS_SUCCESS",
  FETCH_USER_POSTS_FAILURE: "FETCH_USER_POSTS_FAILURE",
};
